baseURL: "https://gislainmarlhens.github.io/gislainmarlhens.github.io/"
languageCode: "en-us"
title: "Gislain Marlhens"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Gislain Marlhens"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Gislain Marlhens" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Gislain."
    subtitle: "Co-op student at CESI engineering school & analyst developer at CEGID"
    content: "Attract by IT since my youngest.  I decided to study this field to evolve and be able to work in what I like.  I would like to work in one of the two that impresses et attract me a lot : Cybersecurity or Artificial Intelligence."
    image: /gislain2.png
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/gislain-marlhens-325945234
      #customIcons:
      # - icon: /fav.png
      #    url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/security.png"
    content: |-
      I am a Co-op student with a passion for computer science. I have some experiences in computer sciences and other fields, and I have a strong interest in the intersection of Cybersecurity and Artificial Intelligence. I am currently working as analyst developer at CEGID in Lyon, France.
      I am currently working on a personnal project to introduce myself in the field of AI and machine learning.
  
    skills:
      enable: true
      title: "Here are a few technologies and softwares I've been working with recently:"
      items:
        - "Python"
        - "Java"
        - "Black Duck"
        - "PowerShell"
        - "Pfsense"
        - "Docker"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Analyst developer"
        company: "CEGID"
        date: "Oct 2022 - present"
        info:
          enable: false
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |
          I am currently working as a analyst developper at CEGID in Lyon, France. My main role is to participate in needs analysis, programming, and the creation of software solutions. I'm working on the security vulnerabilities of the different company's projects.
          - Proficiency in programming languages and development tools necessary to design and develop effective software solutions.
          - Skills in problem-solving and debugging to ensure high-quality software.
          - Ability to work in a team and communicate effectively with team members and stakeholders.
      - job: "Cashier"
        company: "E Leclerc"
        date: "March 2021 - Sep 2022"
        info:
          enable: false
        content: |
          This job involves ensuring accurate management of financial transactions, providing quality customer service, accurately recording purchases, while adhering to security procedures. Key skills include cash handling, customer service, and the ability to manage stress.
          - Ability to work under pressure and manage busy periods.
          - verbal communication skills.
          - Teamwork spirit and flexibility to work according to variable schedules.
          - Precision and attention to detail.
      - job: "Network administrator trainee"
        company: "SDIS 26"
        date: "May 2021 - June 2021"
        info:
          enable: false
        content: |
          As an intern network administrator, I implemented Zabbix monitoring system that allowed monitoring the network of all fire stations in the department. I actively contributed to the establishment of a procedure in the event of ransomware attacks to enhance network security. Additionally, I created a website using wix.
          - Practical knowledge of the Zabbix network monitoring tool.
          - Ability to communicate effectively with the team, present information clearly, and respond to questions.
          - Aptitude to work independently, be proactive, and manage assigned tasks responsibly.

      - job: "IT technician trainee"
        company: "AJC informatique"
        date: "Feb 2027"
        info:
          enable: false
        content: |
          As an intern computer technician, I have gained practical experience in troubleshooting computer issues and providing technical support. I have worked on maintenance and repairsto ensure the proper functioning of systems and software.
          - Ability to work independently and follow instructions.
          - Compétences en maintenance et réparation des équipements informatiques.
      - job: "Seasonal"
        company: "Amblard"
        date: "July 2016 - July 2022"
        info:
          enable: false
        content: |
          As a seasonal worker, I have worked in the agricultural sector, specifically in fruit picking and vineyard labor. I have gained practical experience by participating in fruit harvesting and supporting activities related to viticulture.
          - Physical Fitness: Possessing good physical stamina to handle the physical demands, such as lifting and working outdoors in various weather conditions.
          - Speed and Efficiency: Being able to work quickly and efficiently to maximize productivity and meet harvest deadlines.
          - Team Player: Maintaining a positive attitude and being able to work collaboratively with other team members.   
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Master of Science"
        school:
          name: "CESI engineering school"
          url: "https://www.cesi.fr/en/"
        date: "2022 - 2025"
        content: |-
          Extracurricular Activities
          - Trainee on Udemy
          - Certifications on Coursera
          - Top 4% on TryHackMe
      - title: "2 year technical degree"
        school:
          name: "Algoud-laffemas High School"
        date: "2020 - 2022"
        GPA: "3.5 out of 5.0"
        content: |-
          Second to hackathon's challenge ("La nuit de l'info" Hackathon)<br>
          Extracurricular Activities
          - Basketball
          - Training on Udemy
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "BTEC National Diploma"
        school:
          name: "Algoud-Laffemas High School"
        date: "2018-2020"
        content: |-
          Extracurricular Activities 
            - Basketball
  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: JavaScript training on Udemy
        image: /Udemy.png
        url: https://udemy-certificate.s3.amazonaws.com/image/UC-b843277a-7b3e-4e61-8a23-87ebd141489c.jpg
      - title: TryHackMe - Top 4%
        image: /tryhackme.jpg
       # content: Contributed to a open source project.
        url: https://tryhackme.com/p/gislain.m?show_achievement_badg=blue
      - title: 2nd to Hackathon's challenge
        image: /nuit de l'info.png
       # content: Contributed to a open source project.
      #- title: Google Summer of Code
       # content: Contributed to a open source project.
        #url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: EasySave
        content: This C# Windows application enables secure file backups with encryption. It features a user-friendly interface, automatic scheduling, and a selection of encryption algorithms, ensuring reliable data protection.
        image: /EasySave.png
        badges:
          - "C#"
          - "School Project"
          - "Windows"
      - title: Big Data
        content: During our school project on Big Data, we utilized Talend and Power BI for data processing and visualization. This involved efficiently managing and analyzing large datasets to gain valuable insights.
        image: /BigData.png
        badges:
          - "Power BI"
          - "Talend"
          - "DataBase"
          - "School Project"
      - title: Drawing App
        content: This Android application, developed during a Kotlin training, offers advanced features such as layers, brush size, artwork sharing, and color selection. It allows users to easily create and share their drawings.
        image: DrawingApp.png
        #featured:
         # name: Demo
          #link: https://django-converter.herokuapp.com
        badges:
          - "Kotlin"
          - "Android Studio"
          - "Training"
        #links:
         # - icon: fab fa-github
          #  url: https://github.com/gurusabarish/converter
      - title: Quiz app
        content: During the training, a quiz application about countries was developed. It offers interactive quizzes, multiple-choice questions, and a user-friendly interface for an enjoyable learning experience.
        image: /QuizApp.png
        badges:
          - "Kotlin"
          - "Android Studio"
          - "Training"
      - title: Happy Places
        content: During the training, an application was developed that enables users to catalog and discover iconic landmarks within a dedicated app. Users can easily add and explore significant cultural sites, creating a comprehensive database of renowned locations. With a user-friendly interface, this app provides a convenient way to compile and access a curated collection of cultural landmarks.
        image: /HappyPlaces.png
        badges:
          - "Kotlin"
          - "Android Studio"
          - "Training"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gislain.marlhens@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
     # linkedin: https://linkedin.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"